version: "3.5"
services:
  frontend:
    build: frontend
    container_name: "frontend"
    ports:
      - "80:4200"
    network_mode: "host"
  backend:
    build: backend
    container_name: "backend"
    ports:
      - "8080:8080"
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_ADDRESS}:${POSTGRES_PORT}/${POSTGRES_DB}
      - CLIENT_SECRET=${CLIENT_SECRET}
    volumes:
      - ./backend:/backend
    network_mode: "host"
  db:
    container_name: db
    image: postgres:16.3-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - '5432:${POSTGRES_PORT}'
    volumes:
      - db_hpc:/var/lib/postgresql/data
    network_mode: "host"
volumes:
  db_hpc:
    driver: local
