version: "3.5"
services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: "backend"
    ports:
      - "8080:8080"
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_ADDRESS}:${POSTGRES_PORT}/${POSTGRES_DB}
    volumes:
      - ./backend:/backend
  db:
    container_name: db
    image: postgres:16.3-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - '5432:${POSTGRES_PORT}'
    volumes:
      - db_hpc:/var/lib/postgresql/data
volumes:
  db_hpc:
    driver: local
