/**
 * Usage API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AccessInfo { 
    has_rejected_scc: boolean;
    is_accessible_in_country: boolean;
    is_scc_relevant: boolean;
    needs_to_be_approved: boolean;
    needs_to_confirm_email: boolean;
    needs_to_log_in: boolean;
    user_has_country: boolean;
}

