/**
 * Usage API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Country { 
    geo_location: Country.GeoLocationEnum;
    id: string;
    name: string;
}
export namespace Country {
    export type GeoLocationEnum = 'EU' | 'ADEQUATE' | 'OTHER';
    export const GeoLocationEnum = {
        Eu: 'EU' as GeoLocationEnum,
        Adequate: 'ADEQUATE' as GeoLocationEnum,
        Other: 'OTHER' as GeoLocationEnum
    };
}


