/**
 * Usage API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DatasetWithFileData { 
    accessibility: DatasetWithFileData.AccessibilityEnum;
    approval_type: DatasetWithFileData.ApprovalTypeEnum;
    delphi_share_url: string;
    dua_file_data: string | null;
    dua_file_name: string | null;
    id: string;
    name: string;
    scc_id: string | null;
}
export namespace DatasetWithFileData {
    export type AccessibilityEnum = 'PRIVATE' | 'EU' | 'EU_AND_ADEQUATE' | 'WORLDWIDE' | 'OPEN';
    export const AccessibilityEnum = {
        Private: 'PRIVATE' as AccessibilityEnum,
        Eu: 'EU' as AccessibilityEnum,
        EuAndAdequate: 'EU_AND_ADEQUATE' as AccessibilityEnum,
        Worldwide: 'WORLDWIDE' as AccessibilityEnum,
        Open: 'OPEN' as AccessibilityEnum
    };
    export type ApprovalTypeEnum = 'OVERSIGHT' | 'AUTOMATED';
    export const ApprovalTypeEnum = {
        Oversight: 'OVERSIGHT' as ApprovalTypeEnum,
        Automated: 'AUTOMATED' as ApprovalTypeEnum
    };
}


