/**
 * Usage API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DatasetWithFileData { 
    accessibility: DatasetWithFileData.AccessibilityEnum;
    dua_approval_type: DatasetWithFileData.DuaApprovalTypeEnum;
    dua_file_data: string | null;
    dua_file_name: string | null;
    id: string;
    name: string;
    scc_approval_type: DatasetWithFileData.SccApprovalTypeEnum;
    scc_id: string | null;
}
export namespace DatasetWithFileData {
    export type AccessibilityEnum = 'PRIVATE' | 'EU' | 'EU_AND_ADEQUATE' | 'WORLDWIDE' | 'PUBLIC';
    export const AccessibilityEnum = {
        Private: 'PRIVATE' as AccessibilityEnum,
        Eu: 'EU' as AccessibilityEnum,
        EuAndAdequate: 'EU_AND_ADEQUATE' as AccessibilityEnum,
        Worldwide: 'WORLDWIDE' as AccessibilityEnum,
        Public: 'PUBLIC' as AccessibilityEnum
    };
    export type DuaApprovalTypeEnum = 'OVERSIGHT' | 'AUTOMATED';
    export const DuaApprovalTypeEnum = {
        Oversight: 'OVERSIGHT' as DuaApprovalTypeEnum,
        Automated: 'AUTOMATED' as DuaApprovalTypeEnum
    };
    export type SccApprovalTypeEnum = 'OVERSIGHT' | 'AUTOMATED';
    export const SccApprovalTypeEnum = {
        Oversight: 'OVERSIGHT' as SccApprovalTypeEnum,
        Automated: 'AUTOMATED' as SccApprovalTypeEnum
    };
}


