/**
 * Usage API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AccessInfo } from './accessInfo';


export interface DatasetDetails { 
    access_info: AccessInfo;
    accessibility: DatasetDetails.AccessibilityEnum;
    approval_type: DatasetDetails.ApprovalTypeEnum;
    delphi_share_url: string | null;
    dua_file_name: string | null;
    id: string;
    institution_scc_accepted: boolean | null;
    name: string;
    scc_file_name: string | null;
    scc_id: string | null;
}
export namespace DatasetDetails {
    export type AccessibilityEnum = 'PRIVATE' | 'EU' | 'EU_AND_ADEQUATE' | 'WORLDWIDE' | 'PUBLIC';
    export const AccessibilityEnum = {
        Private: 'PRIVATE' as AccessibilityEnum,
        Eu: 'EU' as AccessibilityEnum,
        EuAndAdequate: 'EU_AND_ADEQUATE' as AccessibilityEnum,
        Worldwide: 'WORLDWIDE' as AccessibilityEnum,
        Public: 'PUBLIC' as AccessibilityEnum
    };
    export type ApprovalTypeEnum = 'OVERSIGHT' | 'AUTOMATED';
    export const ApprovalTypeEnum = {
        Oversight: 'OVERSIGHT' as ApprovalTypeEnum,
        Automated: 'AUTOMATED' as ApprovalTypeEnum
    };
}


