/**
 * Usage API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface InstitutionWithoutId { 
    contact: string;
    country_id: string | null;
    name: string;
    scc_acceptance: InstitutionWithoutId.SccAcceptanceEnum | null;
}
export namespace InstitutionWithoutId {
    export type SccAcceptanceEnum = 'ACCEPT' | 'DO_NOT_ACCEPT' | 'null';
    export const SccAcceptanceEnum = {
        Accept: 'ACCEPT' as SccAcceptanceEnum,
        DoNotAccept: 'DO_NOT_ACCEPT' as SccAcceptanceEnum,
        Null: 'null' as SccAcceptanceEnum
    };
}


