/**
 * Usage API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RegisterRequest { 
    access_protection: string;
    address: string;
    captcha_response: string;
    email: string;
    first_name: string;
    institution_name: string;
    last_name: string;
    password: string;
    storage_protection: string;
}

