/**
 * Usage API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserInfo { 
    access_protection: string;
    address: string;
    approved_at: string | null;
    created_at: string;
    email: string;
    first_name: string;
    id: string;
    institution_id: string;
    institution_name: string;
    is_admin: boolean;
    last_name: string;
    storage_protection: string;
}

