/**
 * Usage API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserDataset { 
    access_granted_by_admin_at: string | null;
    access_requested_at: string | null;
    dataset_id: string;
    delphi_share_created_at: string | null;
    email_sent_to_admin_at: string | null;
    signed_dua_file_data: string | null;
    signed_dua_file_name: string | null;
    user_accepted_dua_at: string | null;
    user_email: string;
    user_id: string;
}

